### ISSUE TITLE
crawler usage on goals fixed at 140%

### ISSUE THREAD

**Issue by stevietv** [Updownquark/OGame-ROI#3]
Resource Settings Tab

no matter what percentage of use the Crawlers are set at in Current side (left), they remain fixed at 140% in goals.

**Comment by Updownquark** [comment]
Do you still see this bug?

**Comment by stevietv** [comment]
yep.

![image](https://user-images.githubusercontent.com/1117625/94360145-a73afa80-00ab-11eb-9b46-f36f02a6d9bc.png)

Yellow highlighted shows the three upgrades planned for this planet.
Green highlighted shows a net energy of 9075 - enough to power the crawler at 150%
difference in the crawler energy usage is `90400-81360 = 9040`

**Comment by stevietv** [comment]
just to add, even on a planet with no upgrades planned, the crawler still sets to 140%.

**Comment by Updownquark** [comment]
This seems to be working with my settings.  Would you mind sending me your XML?  If you don't feel comfortable posting it here you can send it to Updownquark@gmail.com

**Comment by stevietv** [comment]
xml uploaded here:
[OGameUI.xml.txt](https://github.com/Updownquark/OGame-ROI/files/5293801/OGameUI.xml.txt)

renamed to .txt so I could upload it, github doesn't allow xml attachments...

**Comment by Updownquark** [comment]
Was able to replicate the bug with your data and I believe I've fixed it.  Please feel free to reopen this if you see it again.

**Comment by stevietv** [comment]
It appears somewhat resolved, but only when sufficient energy is planned alongside the mine upgrade. If insufficient energy is provided in the goals then it calculates utilisation inaccuratly:

**1. crystal mine upgrade 34 to 35 with no other upgrades**
goal crawler settings show 110% of utilization after an upgrade of crystal mine, (note that here no solar sats are added to upgrades.)
however net energy shows 35032 - that's surely enough to get higher than 110%.
![image](https://user-images.githubusercontent.com/1117625/94489537-e882f580-01e4-11eb-9727-a0d928ede7e4.png)


**2. crystal mine upgrade 34 to 35 with sufficient solar sats, leads to 150% utilization**

![image](https://user-images.githubusercontent.com/1117625/94490007-dce3fe80-01e5-11eb-89a3-e9a0a693f405.png)

**Comment by Updownquark** [comment]
Indeed, tyvm

**Comment by Updownquark** [comment]
This should be fixed in the latest.  Let me know, please

**Comment by stevietv** [comment]
A few issues now caused by this.

1. planets with no goals show no production on the goals side:

![image](https://user-images.githubusercontent.com/1117625/94651331-9c28da00-02f8-11eb-93ac-f96f16640338.png)


2a. planets with a goal show only base income, slot bonus and energy usage:
2b. Planets with a goal show 150% utilization of crawler, even though that should be tuned down to 140% right given the net energy of -1143?

![image](https://user-images.githubusercontent.com/1117625/94651411-b5ca2180-02f8-11eb-8b0b-4d55d62f09b9.png)

**Comment by Updownquark** [comment]
I noticed the no production display issue last night.

I'll need to check, but it's possible that the 10% crawler bump is more
significant than the energy hit.

**Comment by Updownquark** [comment]
Actually, it's more likely that it's just nonsense due to missing production values.  I've fixed this, will push it and make a new release in a bit.

**Comment by stevietv** [comment]
planets with no goals appear fixed, however a planet with a goal still shows no production:

![image](https://user-images.githubusercontent.com/1117625/94865495-fe3f2780-043d-11eb-87b0-34a511a82696.png)

**Comment by Updownquark** [comment]
I believe this was a symptom of #8, which should be fixed in v0.9.10.
